apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-produto-dev

namePrefix: dev-

commonLabels:
  environment: development

resources:
- ../../base

replicas:
- name: api-produto
  count: 1

images:
- name: api_produto
  newTag: dev

configMapGenerator:
- name: api-produto-config
  behavior: merge
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=debug

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: api-produto
