apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-produto

namePrefix: prod-

commonLabels:
  environment: production

resources:
- ../../base

replicas:
- name: api-produto
  count: 3

images:
- name: api_produto
  newTag: latest

configMapGenerator:
- name: api-produto-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=warn

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: api-produto
