apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-produto-staging

namePrefix: staging-

commonLabels:
  environment: staging

resources:
- ../../base

replicas:
- name: api-produto
  count: 2

images:
- name: api_produto
  newTag: staging

configMapGenerator:
- name: api-produto-config
  behavior: merge
  literals:
  - ENVIRONMENT=staging
  - LOG_LEVEL=info

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: api-produto
