name: api_produto
description: API REST CRUD de produtos em Dart
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  http: ^1.1.0
